apiApi:
  image: us-east1-docker.pkg.dev/v1-mvp/api/api
  tag: latest
  replicas: 1
  port: 8000

apiBe:
  image: us-east1-docker.pkg.dev/v1-mvp/be-api/backend
  tag: latest
  replicas: 1
  port: 8000

apiDb:
  image: mysql
  tag: "8.0"
  port: 3306

ingress:
  host: api.ppa-dun.site
