services:
  fe:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /app/api/frontend:/usr/share/nginx/html:ro
    depends_on:
      - be
    restart: unless-stopped

  be:
    build: /app/be
    ports:
      - "8080:8080"
    restart: unless-stopped
