ppaDunFe:
  image: us-east1-docker.pkg.dev/v1-mvp/fe-prod/fe
  tag: "8d8cec0e4cc65d47e6c9a048eda565f9f0298caa"
  replicas: 1
  port: 80

ppaDunBe:
  image: us-east1-docker.pkg.dev/v1-mvp/be-prod/be
  tag: "a4f4ec882e609a0f62b0bbf6936d332616f18842"
  replicas: 1
  port: 8080

env: dev

ingress:
  host: ppa-dun.site
