apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  ENV: {{ .Values.env | default "dev" }}
  CORS_ORIGINS: {{ .Values.api.corsOrigins | default "*" }}
  EXTERNAL_API_BASE_URL: {{ .Values.api.externalApiBaseUrl | default "" }}
  EXTERNAL_API_KEY: {{ .Values.api.externalApiKey | default "" }}
  EXTERNAL_API_TIMEOUT_SECONDS: {{ .Values.api.externalApiTimeout | default "5.0" | quote }}
