apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ppa-dun-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ppa-dun-secret-store
    kind: SecretStore
  target:
    name: ppa-dun-secret
    creationPolicy: Owner
  data:
    - secretKey: EXTERNAL_API_KEY
      remoteRef:
        key: external-api-key
    - secretKey: EXTERNAL_API_BASE_URL
      remoteRef:
        key: external-api-base-url
    - secretKey: DB_USER
      remoteRef:
        key: db-user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-password
    - secretKey: DB_HOST
      remoteRef:
        key: db-host
    - secretKey: DB_PORT
      remoteRef:
        key: db-port
    - secretKey: DB_NAME
      remoteRef:
        key: db-name
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: db-password
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: db-name
