apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: ppa-dun-updater
  namespace: argocd
spec:
  applications:
    - name: PPA-DUN
      images:
        - name: ppa-dun-fe
          image: us-east1-docker.pkg.dev/v1-mvp/fe-prod/fe
          strategy: digest
        - name: ppa-dun-be
          image: us-east1-docker.pkg.dev/v1-mvp/be-prod/be
          strategy: digest
