apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: ppa-dun-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "ppa-dun"
      images:
        - alias: fe
          imageName: us-east1-docker.pkg.dev/v1-mvp/fe-prod/fe:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: be
          imageName: us-east1-docker.pkg.dev/v1-mvp/be-prod/be:latest
          commonUpdateSettings:
            updateStrategy: digest
