apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: ppa-dun-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "PPA-DUN"
      images:
        - image: us-east1-docker.pkg.dev/v1-mvp/fe-prod/fe
          name: ppa-dun-fe
          updateStrategy: digest
        - image: us-east1-docker.pkg.dev/v1-mvp/be-prod/be
          name: ppa-dun-be
          updateStrategy: digest
