apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "api-lb"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: api-api
                port:
                  number: 80
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: api-be
                port:
                  number: 80
          - path: /demo
            pathType: Prefix
            backend:
              service:
                name: api-api
                port:
                  number: 80
          - path: /player
            pathType: Prefix
            backend:
              service:
                name: api-api
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-api
                port:
                  number: 80
